version: "3"
services:
  node-app:
    build: .
    environment:
      - PORT=3000
    volumes:
      - mongo-db-named-volume:/data/db
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:7.0.2-jammy
  redis:
    image: redis:alpine3.18
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  mongo-db-named-volume: